# Generated by Django 3.2.5 on 2021-07-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=30)),
                ('book_writer', models.CharField(default='', max_length=20)),
                ('book_price', models.IntegerField(default=0)),
                ('book_discount', models.IntegerField(default=0)),
            ],
        ),
    ]
