# Generated by Django 3.2.5 on 2021-07-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdetails',
            name='book_imgs',
            field=models.ImageField(default='', upload_to='books/images'),
        ),
    ]
